### ISSUE TITLE
Additions to Next release - v2.8.0

### ISSUE THREAD

**Issue by IkelAtomig** [libredirect/browser_extension#768]
- [x] Remove Beatbump cuz it doesn't follow the URL schemes. So, the extension could redirect. We will be switching to Hyperpipe as default and the only one until anything new pops up.
- [x] Stick to the default variable when switching frontends for Redirect type in YouTube. Instead of being separate.
- [x] Really need to check Wolfram Alpha as it is weirder and need to check if the project is still good to be in the extension.
- [x] #754 
- [x] Grey out sync options in Chromium browser until support is made available with a message only available on Firefox based browsers.
- [x] Supporting Redirect, Redirect to Original and Copy Raw functions when instance used is `localhost`. #767 
- [x] Add Github Gists support in Gothub. #761 
- [x] #748 
- [x] Re-add Destructables [#97](https://codeberg.org/LibRedirect/browser_extension/issues/97).

---

P.S. Things that I noticed in my Radar are listed here. Other open issues will be looked and could be added.

Comments are welcome regarding the features don't like. But open a new issue and reference this one there. To keep it tidy.

**Comment by ManeraKai** [comment]
> Stick to the default variable when switching frontends for Redirect type in YouTube. Instead of being separate

This is already implemented?

**Comment by ManeraKai** [comment]
>  Hide Unsupported iframes handling option for frontends that don't support it.

You counter argued yourself, this option IS for the urls that the frontends don't support.

**Comment by IkelAtomig** [comment]
Then rename it as URLs when we don't replace embeds for a frontend.

**Comment by ManeraKai** [comment]
You still didn't understand it, it was before `Unsupported urls handling`, but we changed it to `Unsupported iframes handling` bc it is only for iframes. Say Piped-Material doesn't support iframes, so we need an option to tell LibRedirect to either bypass any youtube iframe or block it entirely, hence `Unsupported iframes handling` exists.

**Comment by IkelAtomig** [comment]
Just keep it as iframes handling for YouTube, Twitter and rename as URLs for other frontends. I guess that would make sense and avoid confusion.

**Comment by ManeraKai** [comment]
for other frontends they may have iframes too, and the option doesn't do anything other than iframes my man.

**Comment by IkelAtomig** [comment]
Well, it could be reused then. For example, IMDb frontend still doesn't support few URLs such as Movie company info - https://imdb.com/company/co0485456?ref_=tt_dt_co_1. For these, when we set it to bypass, it loads IMdb or loads libremdb when set to block. That is how it should function.

If renamed as unsupported URLs handling. But in the case of iframes, only YouTube, Twitter, Imgur, Reddit and possibly, Bandcamp has iframes. So, either hide it for other frontends or rename it.

**Comment by ManeraKai** [comment]
https://github.com/libredirect/browser_extension/issues/648
